import type { ProviderDefinition, ProviderId } from './types'

export const PROVIDER_REGISTRY: Record<ProviderId, ProviderDefinition> = {
  ollama: {
    id: 'ollama',
    name: 'Ollama',
    kind: 'ollama',
    billingMode: 'subscription',
    defaultModel: 'gpt-oss:120b-cloud',
    localFallbackModel: 'qwen2.5-coder:latest',
    description: 'Ollama Pro cloud + local models. Default always-on provider. No separate API billing.',
    setupCommand: 'ollama signin',
    docsUrl: 'https://ollama.com',
    models: ['gpt-oss:120b-cloud', 'qwen2.5-coder:latest', 'llama3', 'llama3.2', 'mistral', 'deepseek-coder', 'hermes3'],
    color: '#F97316',
  },
  'claude-code': {
    id: 'claude-code',
    name: 'Claude Code',
    kind: 'cli-subscription',
    billingMode: 'subscription',
    defaultModel: 'claude',
    description: 'Claude via Claude Code CLI. Uses your Anthropic Pro subscription. No API billing.',
    setupCommand: 'claude login',
    docsUrl: 'https://claude.ai/code',
    models: ['claude'],
    color: '#8B5CF6',
  },
  'gemini-cli': {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    kind: 'cli-subscription',
    billingMode: 'subscription',
    defaultModel: 'gemini',
    description: 'Gemini via local CLI. Uses your Google One AI Premium subscription. No API billing.',
    setupCommand: 'gemini auth login',
    docsUrl: 'https://ai.google.dev',
    models: ['gemini'],
    color: '#3B82F6',
  },
  'codex-cli': {
    id: 'codex-cli',
    name: 'Codex CLI',
    kind: 'cli-subscription',
    billingMode: 'subscription',
    defaultModel: 'codex',
    description: 'OpenAI Codex via local CLI. Uses your ChatGPT subscription. No API billing.',
    setupCommand: 'codex login',
    docsUrl: 'https://github.com/openai/codex',
    models: ['codex'],
    color: '#10B981',
  },
  'openclaw-cli': {
    id: 'openclaw-cli',
    name: 'OpenClaw',
    kind: 'cli-subscription',
    billingMode: 'local',
    defaultModel: 'openclaw',
    description: 'Local OpenClaw assistant bridge. Best when launched/configured through Ollama or OpenClaw onboard, then called through the BertOS desktop daemon.',
    setupCommand: 'ollama launch openclaw --config, or npm install -g openclaw@latest && openclaw onboard --install-daemon',
    docsUrl: 'https://docs.ollama.com/integrations/openclaw',
    models: ['openclaw', 'openclaw+ollama'],
    color: '#EF4444',
    capabilities: ['local-agent', 'ollama-backed', 'messaging-gateway', 'tool-orchestration', 'desktop-daemon'],
  },
  'claude-api': {
    id: 'claude-api',
    name: 'Anthropic API',
    kind: 'api-optional',
    billingMode: 'api',
    defaultModel: 'claude-opus-4-5',
    description: 'Direct Anthropic API access.',
    billingWarning: 'ChatGPT Plus / Claude Pro do NOT include API credits. Enabling this creates a separate metered bill.',
    setupCommand: 'Set ANTHROPIC_API_KEY env var',
    docsUrl: 'https://docs.anthropic.com',
    models: ['claude-opus-4-5', 'claude-3-5-sonnet-latest'],
    color: '#8B5CF6',
  },
  'openai-api': {
    id: 'openai-api',
    name: 'OpenAI API',
    kind: 'api-optional',
    billingMode: 'api',
    defaultModel: 'gpt-4o',
    description: 'Direct OpenAI API access.',
    billingWarning: 'ChatGPT Plus does NOT include API credits. Enabling this creates a separate metered bill.',
    setupCommand: 'Set OPENAI_API_KEY env var',
    docsUrl: 'https://platform.openai.com/docs',
    models: ['gpt-4o', 'gpt-4o-mini'],
    color: '#10B981',
  },
  'gemini-api': {
    id: 'gemini-api',
    name: 'Gemini API',
    kind: 'api-optional',
    billingMode: 'api',
    defaultModel: 'gemini-2.0-flash',
    description: 'Direct Google Gemini API access.',
    billingWarning: 'Google One AI Premium does NOT include Gemini API credits. Enabling this creates a separate metered bill.',
    setupCommand: 'Set GEMINI_API_KEY env var',
    docsUrl: 'https://ai.google.dev/docs',
    models: ['gemini-2.0-flash', 'gemini-1.5-pro'],
    color: '#3B82F6',
  },
  'gemini-api-native': {
    id: 'gemini-api-native',
    name: 'Gemini Native API',
    kind: 'api-native',
    billingMode: 'api',
    defaultModel: 'gemini-2.5-pro',
    description: 'Native Google GenAI SDK provider for structured planning, long context, council judging, and system analysis.',
    billingWarning: 'Google One AI Premium does NOT include Gemini API credits. Enabling this creates a separate metered bill.',
    setupCommand: 'Set GEMINI_API_KEY env var. GOOGLE_API_KEY is also supported as a fallback.',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    models: ['gemini-2.5-pro', 'gemini-2.5-flash'],
    color: '#3B82F6',
    capabilities: ['chat', 'structured-json', 'long-context', 'planning', 'code-analysis', 'council-judge', 'workspace-planning', 'multimodal-foundation'],
    requiredEnvVars: ['GEMINI_API_KEY'],
  },
  'hermes-nous': {
    id: 'hermes-nous',
    name: 'Hermes Agent',
    kind: 'api-native',
    billingMode: 'local',
    defaultModel: 'hermes-agent',
    description: 'Server-side OpenAI-compatible Hermes Agent connector for Hostinger VPS, local Ollama-backed Hermes, or a custom free endpoint.',
    billingWarning: 'BertOS does not require OpenAI, Anthropic, Claude, or paid OpenRouter keys for Hermes. Any model cost depends on the Hermes backend you configure.',
    setupCommand: 'Set HERMES_ENABLED=true, HERMES_BASE_URL=http://127.0.0.1:8642/v1 or HTTPS /v1 endpoint, HERMES_API_KEY, and HERMES_MODEL=hermes-agent server-side.',
    docsUrl: 'https://www.hostinger.com/support/how-to-get-started-with-hermes-agent-at-hostinger/',
    models: ['hermes-agent'],
    color: '#A855F7',
    capabilities: ['chat', 'openai-compatible-api', 'remote-agent', 'hostinger-vps', 'ollama-local-backend', 'custom-endpoint'],
    requiredEnvVars: ['HERMES_ENABLED', 'HERMES_BASE_URL', 'HERMES_API_KEY'],
  },
}

export const SUBSCRIPTION_PROVIDERS: ProviderId[] = ['ollama', 'claude-code', 'gemini-cli', 'codex-cli', 'openclaw-cli']
export const API_PROVIDERS: ProviderId[] = ['claude-api', 'openai-api', 'gemini-api', 'gemini-api-native', 'hermes-nous']
export const DEFAULT_PROVIDER: ProviderId = 'ollama'
export const DEFAULT_PROVIDER_MODEL = 'gpt-oss:120b-cloud'
export const LOCAL_FALLBACK_MODEL = 'qwen2.5-coder:latest'
export const DEFAULT_OLLAMA_ENDPOINT = 'http://127.0.0.1:11434'
