import { askWithProviderRouter, getVerifiedProviderStatuses } from '../providers/router'
import { PATCH_COMPILER_INSTRUCTIONS, parseCanonicalPatch } from '../patch/schema'
import type { AIModel } from '../types'
import { requireProject } from './projects'
import { readProjectFile } from './files'
import { createPatchProposal } from './patches'
import { isPaidProvider } from './provider-hub'
import { CodingOSError, type PatchProposal } from './types'

export interface PatchFromProviderResult {
  ok: boolean
  patch?: PatchProposal
  providerName?: string
  providerId?: string
  reason?: string
  draft?: string
  outputId?: string
}

/**
 * Ask a provider for a structured patch and parse it into an approval-gated PatchProposal.
 * Never applies; invalid provider output is saved as a draft for repair.
 */
export async function generatePatchFromProvider(input: {
  projectId: string
  request: string
  paths?: string[]
  providerId?: string
  allowPaid?: boolean
}): Promise<PatchFromProviderResult> {
  const project = await requireProject(input.projectId)
  const request = (input.request ?? '').trim()
  if (!request) throw new CodingOSError('invalid-input', 'A change request is required.')

  if (input.providerId && isPaidProvider(input.providerId) && !input.allowPaid) {
    return { ok: false, providerId: input.providerId, reason: 'Paid provider — enable paid usage to generate a patch with it.' }
  }

  const statuses = await getVerifiedProviderStatuses().catch(() => [])
  const onlineIds = statuses.filter(s => s.online).map(s => s.providerId)
  if (onlineIds.length === 0) {
    return { ok: false, reason: 'No AI provider is online. Patch generation needs a provider (e.g. start Ollama or a CLI). Use the Patch Forge to author one manually.' }
  }

  // Gather current content of the target files (safe reads; secrets redacted) for context.
  const fileBlocks: string[] = []
  for (const rel of (input.paths ?? []).slice(0, 8)) {
    try {
      const file = await readProjectFile(input.projectId, rel)
      fileBlocks.push(`FILE: ${rel}\n\`\`\`\n${file.content.slice(0, 12000)}\n\`\`\``)
    } catch {
      fileBlocks.push(`FILE: ${rel}\n(could not read — it may be new, sensitive, or binary)`)
    }
  }

  const prompt = [
    PATCH_COMPILER_INSTRUCTIONS,
    '',
    `Project: ${project.name} at ${project.repoPath}`,
    'Only modify files that are clearly part of this project. Never touch .env, keys, or credentials.',
    fileBlocks.length ? `\nCurrent file contents:\n${fileBlocks.join('\n\n')}` : '\n(No file contents provided — base your patch on the request and create new files where needed.)',
    '',
    `Change request: ${request}`,
  ].join('\n')

  const preferred = (input.providerId ?? 'auto') as AIModel
  const result = await askWithProviderRouter(prompt, preferred, {
    purpose: 'patch', mode: 'patch', temperature: 0, maxTokens: 4096,
    deprioritizedProviders: input.allowPaid ? [] : ['gemini-api-native'],
  })
  if (!result.ok || !result.text.trim()) {
    return { ok: false, providerId: result.selectedProvider, providerName: result.providerName, reason: result.error || 'Provider returned no patch.' }
  }

  let canonical
  try {
    canonical = parseCanonicalPatch(result.text)
  } catch (error) {
    // Save the raw output as a draft artifact for later repair.
    let outputId: string | undefined
    try {
      const { createOutputArtifact } = await import('../outputs/registry')
      const artifact = await createOutputArtifact({
        type: 'patch_proposal', title: `Unparsed patch draft: ${request.slice(0, 50)}`,
        project: project.slug, status: 'draft', tags: ['coding-os', 'patch', 'draft', 'needs-repair'],
        content: `# Provider output could not be parsed into a patch\n\nRequest: ${request}\n\n## Raw output\n\n\`\`\`\n${result.text.slice(0, 40000)}\n\`\`\``,
        fileName: 'patch-draft.md',
      })
      outputId = artifact.outputId
    } catch { /* best-effort */ }
    return { ok: false, providerId: result.selectedProvider, providerName: result.providerName, reason: `Provider output was not a valid patch: ${error instanceof Error ? error.message : 'parse failed'}. Saved as a draft for repair.`, draft: result.text.slice(0, 4000), outputId }
  }

  try {
    const patch = await createPatchProposal(input.projectId, {
      title: canonical.summary?.slice(0, 120) || `Patch: ${request.slice(0, 60)}`,
      description: `Generated by ${result.providerName || result.selectedProvider} from request: ${request}`,
      reason: request,
      files: canonical.files.map(f => ({
        path: f.path,
        action: f.action === 'update' ? 'modify' : f.action,
        after: f.action === 'delete' ? undefined : f.content,
      })),
      validationPlan: canonical.validation?.commands,
    })
    return { ok: true, patch, providerId: result.selectedProvider, providerName: result.providerName || result.selectedProvider }
  } catch (error) {
    // Safety rejection (traversal / sensitive file / conflict) — surfaced, not applied.
    return { ok: false, providerId: result.selectedProvider, providerName: result.providerName, reason: error instanceof Error ? error.message : 'Patch was rejected by safety checks.' }
  }
}
