import type { CommandCenterAgentId } from '@/lib/bertos/command-center'
import { routePrompt } from '@/lib/bertos/router'

export type AgentTeamId =
  | 'coding-team'
  | 'content-team'
  | 'seo-lead-gen-team'
  | 'daily-chief-of-staff-team'
  | 'bertos-maintenance-team'

export type AgentTeamStatus = 'prompt-orchestrated' | 'partially-live' | 'planned'

export interface AgentTeamMember {
  id: string
  name: string
  role: string
  narrowJob: string
  skills: string[]
  memory: string
  visibleWorkOutput: string
  debuggingProof: string
  bestProvider: CommandCenterAgentId | 'manual'
  status: 'live' | 'copy-prompt' | 'planned'
  requiresDaemon: boolean
  requiresApiKey: boolean
  billingMode: string
  canRunNow: string
  plannedCapabilities: string[]
  copyPromptTemplate: string
  warning?: string
}

export interface AgentTeam {
  id: AgentTeamId
  name: string
  purpose: string
  bestUse: string
  status: AgentTeamStatus
  nextSetupStep: string
  workflow: string[]
  agents: AgentTeamMember[]
}

const COMMON_SAFETY = [
  'Do not touch Sylistly or unrelated projects.',
  'Do not print secrets or read .env.local contents.',
  'Do not push, auto-merge, deploy, or spend paid credits without explicit approval.',
  'Label planned/copy-prompt tools honestly.',
  'Run npm run typecheck, npm run build, and npm run bertos:safety for code changes.',
]

function member(input: AgentTeamMember): AgentTeamMember {
  return input
}

export const AGENT_TEAMS: AgentTeam[] = [
  {
    id: 'coding-team',
    name: 'Coding Team',
    purpose: 'Turn scoped BertOS or app tasks into safe implementation, verification, review, and memory handoff.',
    bestUse: 'UI repairs, build fixes, provider routing work, repo audits, PR review, and self-coding workflow improvements.',
    status: 'partially-live',
    nextSetupStep: 'Start npm run bertos:daemon so Claude Code, Codex, and Gemini CLI can be reached through the local bridge.',
    workflow: [
      'Orchestrator breaks the task into phases and assigns files.',
      'Claude Code handles UI/architecture implementation or review.',
      'Codex verifies typecheck/build/safety and fixes direct errors.',
      'Devin can receive a scoped PR prompt when external cloud teammate workflow is desired.',
      'Provider Health Auditor confirms paid gates and provider status honesty.',
      'Memory Logger writes the session summary for future agents.',
    ],
    agents: [
      member({
        id: 'coding-orchestrator',
        name: 'Orchestrator',
        role: 'Task decomposer and safety gate.',
        narrowJob: 'Convert the rough task into phases, likely files, constraints, and validation.',
        skills: ['mission planning', 'risk scoring', 'handoffs'],
        memory: 'Uses AGENTS.md, README, BERTOS_AUTONOMOUS_PROGRESS.md, and current route state.',
        visibleWorkOutput: 'Phased mission plan and provider assignment.',
        debuggingProof: 'Lists assumptions, blocked items, and exact validation commands.',
        bestProvider: 'bertos-orchestrator',
        status: 'live',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local UI',
        canRunNow: 'Yes for prompt generation.',
        plannedCapabilities: ['persistent task graph', 'worktree assignment'],
        copyPromptTemplate: 'Break this BertOS task into phases, assign each phase to the right provider, and keep safety gates active.',
      }),
      member({
        id: 'claude-ui-engineer',
        name: 'Claude Code UI Engineer',
        role: 'Architecture and UI implementation specialist.',
        narrowJob: 'Implement or review React/Next.js UI changes with strong component quality.',
        skills: ['React UI', 'layout repair', 'architecture review'],
        memory: 'Uses existing component patterns and command-center safety rules.',
        visibleWorkOutput: 'Reviewable patch or UI risk report.',
        debuggingProof: 'Names changed components and visual/runtime checks.',
        bestProvider: 'claude-code',
        status: 'copy-prompt',
        requiresDaemon: true,
        requiresApiKey: false,
        billingMode: 'CLI/subscription',
        canRunNow: 'Requires Claude Code CLI plus daemon.',
        plannedCapabilities: ['direct patch application through approval queue'],
        copyPromptTemplate: 'Use Claude Code to implement the UI/architecture part only. Keep changes scoped and report files changed.',
      }),
      member({
        id: 'codex-build-verifier',
        name: 'Codex Build Verifier',
        role: 'Build, route smoke, PR review, and safety verifier.',
        narrowJob: 'Run typecheck/build/safety, inspect failures, and patch direct causes.',
        skills: ['TypeScript', 'build triage', 'route smoke', 'PR review'],
        memory: 'Uses validation logs, git diff, and provider registry notes.',
        visibleWorkOutput: 'Validation transcript and direct fix patch.',
        debuggingProof: 'Reports exact command results and failed route/status if any.',
        bestProvider: 'codex-cli',
        status: 'copy-prompt',
        requiresDaemon: true,
        requiresApiKey: false,
        billingMode: 'CLI/subscription',
        canRunNow: 'Requires Codex CLI plus daemon.',
        plannedCapabilities: ['automated validation lane after patch approval'],
        copyPromptTemplate: 'Use Codex as build verifier. Run typecheck, build, safety, and route smoke; fix only direct failures.',
      }),
      member({
        id: 'devin-pr-teammate',
        name: 'Devin PR Teammate',
        role: 'External scoped PR teammate.',
        narrowJob: 'Take a narrow prompt and return a reviewable PR without auto-merge.',
        skills: ['cloud PR workflow', 'issue triage', 'route smoke'],
        memory: 'Uses copied mission context only.',
        visibleWorkOutput: 'PR summary, changed files, and validation evidence.',
        debuggingProof: 'Links failures to exact files and commands in the PR report.',
        bestProvider: 'devin',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'external cloud service',
        canRunNow: 'Copy-prompt only from BertOS.',
        plannedCapabilities: ['optional safe Devin API status bridge'],
        copyPromptTemplate: 'Create a scoped Devin PR task. Do not auto-merge, do not push from BertOS, and report validation evidence.',
      }),
      member({
        id: 'provider-health-auditor',
        name: 'Provider Health Auditor',
        role: 'Provider registry and paid-gate checker.',
        narrowJob: 'Verify status labels, paid-provider gates, and no fake provider claims.',
        skills: ['provider status', 'settings audit', 'billing safety'],
        memory: 'Uses Settings provider cards and /api/providers/status.',
        visibleWorkOutput: 'Provider health report and recommended fixes.',
        debuggingProof: 'Shows which endpoints/cards were inspected.',
        bestProvider: 'codex-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local inspection',
        canRunNow: 'Yes as a copied audit prompt; daemon helps with CLI checks.',
        plannedCapabilities: ['scheduled Autopilot provider audit'],
        copyPromptTemplate: 'Audit BertOS provider status and paid gates. Do not make paid calls or expose secrets.',
      }),
      member({
        id: 'coding-memory-logger',
        name: 'Memory Logger',
        role: 'Session summary and decision recorder.',
        narrowJob: 'Write a compact memory note with changes, validation, decisions, and next prompt.',
        skills: ['summarization', 'decision capture', 'journal handoff'],
        memory: 'Uses progress notes and local memory categories.',
        visibleWorkOutput: 'Memory note text ready for /memory or future Obsidian vault.',
        debuggingProof: 'Includes source session, commands, and limitations.',
        bestProvider: 'ollama-local',
        status: 'live',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local/free or configured Ollama',
        canRunNow: 'Yes as copyable summary prompt.',
        plannedCapabilities: ['Obsidian markdown writer after permissioned daemon support'],
        copyPromptTemplate: 'Summarize this session into a memory note. Include decisions, validation, files changed, and next prompt. No secrets.',
      }),
    ],
  },
  {
    id: 'content-team',
    name: 'Content Team',
    purpose: 'Turn a product/project idea into researched writing, visuals, review, and planned video assets.',
    bestUse: 'Blog posts, launch content, short scripts, thumbnails, newsletters, and social repurposing.',
    status: 'planned',
    nextSetupStep: 'Connect approved research/browser tools and install a verified local video pipeline before claiming generation.',
    workflow: [
      'Orchestrator defines the content angle and output formats.',
      'Researcher gathers evidence only if web/search tools are available.',
      'Content Writer drafts the long-form asset.',
      'Thumbnail Creator writes visual direction and prompt only.',
      'Review Editor tightens claims, tone, and safety.',
      'Hyperframes/Remotion agents stay planned until installed and verified.',
      'Social Repurposer converts the approved asset into short posts.',
    ],
    agents: [
      member({
        id: 'content-orchestrator',
        name: 'Orchestrator',
        role: 'Content workflow planner.',
        narrowJob: 'Define angle, audience, deliverables, and handoff order.',
        skills: ['briefing', 'content strategy', 'workflow planning'],
        memory: 'Uses project goals, prior content notes, and daily brief context.',
        visibleWorkOutput: 'Content brief and production checklist.',
        debuggingProof: 'States data sources used or marks research unavailable.',
        bestProvider: 'gemini-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'CLI/subscription or manual model',
        canRunNow: 'Copy-prompt only unless provider is run externally.',
        plannedCapabilities: ['calendar/content queue integration'],
        copyPromptTemplate: 'Plan a content package from this idea. List assumptions, deliverables, and what research is missing.',
      }),
      member({
        id: 'content-researcher',
        name: 'Researcher',
        role: 'Evidence and trend collector.',
        narrowJob: 'Find what is working and summarize sources when tools are available.',
        skills: ['research', 'trend synthesis', 'source notes'],
        memory: 'Uses daily journal and content performance notes when present.',
        visibleWorkOutput: 'Research summary with source limitations.',
        debuggingProof: 'Separates verified facts from assumptions.',
        bestProvider: 'gemini-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'provider/tool dependent',
        canRunNow: 'Copy-prompt only unless browser/search tools are connected.',
        plannedCapabilities: ['web search connector', 'competitor tracker'],
        copyPromptTemplate: 'Research current trends for this topic if web tools exist. If not, say what data is missing and avoid guessing.',
      }),
      member({
        id: 'content-writer',
        name: 'Content Writer',
        role: 'Drafting agent.',
        narrowJob: 'Write the main content asset from an approved brief.',
        skills: ['long-form writing', 'positioning', 'clarity'],
        memory: 'Uses brand voice and project notes.',
        visibleWorkOutput: 'Blog/script/newsletter draft.',
        debuggingProof: 'Lists intended audience and claims that need verification.',
        bestProvider: 'qwen-experimental',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'manual/API dependent',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['style memory', 'editorial calendar'],
        copyPromptTemplate: 'Draft the content from this brief. Keep claims clearly marked if not verified.',
      }),
      member({
        id: 'thumbnail-creator',
        name: 'Thumbnail Creator',
        role: 'Visual concept agent.',
        narrowJob: 'Generate thumbnail concept, composition notes, and image prompt.',
        skills: ['visual direction', 'thumbnail hooks', 'prompt writing'],
        memory: 'Uses previous visual decisions and content category.',
        visibleWorkOutput: 'Thumbnail brief and prompt.',
        debuggingProof: 'Explains hook, contrast, and required assets.',
        bestProvider: 'manual',
        status: 'planned',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'design tool dependent',
        canRunNow: 'Prompt only; no image tool is wired in BertOS.',
        plannedCapabilities: ['Canva/Figma/image-generation approval workflow'],
        copyPromptTemplate: 'Create a thumbnail concept and prompt. Do not claim an image was generated.',
      }),
      member({
        id: 'review-editor',
        name: 'Review Editor',
        role: 'Quality and claims reviewer.',
        narrowJob: 'Tighten structure, remove unsupported claims, and prepare final edits.',
        skills: ['editing', 'fact-check discipline', 'tone control'],
        memory: 'Uses decisions and known audience notes.',
        visibleWorkOutput: 'Edited content and change notes.',
        debuggingProof: 'Lists removed/changed claims.',
        bestProvider: 'claude-code',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'CLI/subscription or external',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['review queue'],
        copyPromptTemplate: 'Edit this content for clarity, supported claims, and audience fit. Show major changes.',
      }),
      member({
        id: 'hyperframes-video-agent',
        name: 'Hyperframes Video Agent',
        role: 'Planned local HTML/CSS/JS video pipeline.',
        narrowJob: 'Create animated video plan or setup prompt; never claim rendering works until installed.',
        skills: ['HTML/CSS/JS animation planning', 'video storyboard'],
        memory: 'Uses content brief and visual decisions.',
        visibleWorkOutput: 'Storyboard or setup prompt.',
        debuggingProof: 'States install checks required: Node, FFmpeg, Hyperframes.',
        bestProvider: 'hyperframes',
        status: 'planned',
        requiresDaemon: true,
        requiresApiKey: false,
        billingMode: 'local setup dependent',
        canRunNow: 'No. Planned/not installed.',
        plannedCapabilities: ['local render checks', 'asset export'],
        copyPromptTemplate: 'Plan a Hyperframes video pipeline. Verify installation first; do not claim rendering works.',
      }),
      member({
        id: 'social-repurposer',
        name: 'Social Repurposer',
        role: 'Short-form distribution writer.',
        narrowJob: 'Convert one approved asset into platform-specific posts.',
        skills: ['short copy', 'platform adaptation', 'CTA writing'],
        memory: 'Uses audience and previous post notes.',
        visibleWorkOutput: 'LinkedIn, X/Twitter, newsletter, and short-video copy.',
        debuggingProof: 'Explains what was adapted and why.',
        bestProvider: 'qwen-experimental',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'manual/API dependent',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['scheduled drafts', 'approval queue'],
        copyPromptTemplate: 'Repurpose this idea into LinkedIn, X/Twitter, newsletter, and short-video script. Do not auto-post.',
      }),
    ],
  },
  {
    id: 'seo-lead-gen-team',
    name: 'SEO / Lead Gen Team',
    purpose: 'Plan search-led content and outreach without pretending publishing or analytics are connected.',
    bestUse: 'Keyword research prompts, WordPress fix planning, outreach drafts, and analytics review checklists.',
    status: 'planned',
    nextSetupStep: 'Connect approved search/analytics/CMS tools before enabling live publishing or analytics reads.',
    workflow: [
      'SEO Researcher defines target market and seed terms.',
      'Keyword/Trend Scout gathers opportunities when web tools exist.',
      'WordPress Fixer stays planned until a safe CMS route exists.',
      'Content Publisher stays planned and never posts automatically.',
      'Outreach Drafter writes approved messages only.',
      'Analytics Reviewer summarizes data only if analytics exports are provided.',
    ],
    agents: [
      member({
        id: 'seo-researcher',
        name: 'SEO Researcher',
        role: 'Search strategy planner.',
        narrowJob: 'Define keyword clusters and content opportunities.',
        skills: ['SEO strategy', 'SERP thinking', 'content gaps'],
        memory: 'Uses project goals and prior content notes.',
        visibleWorkOutput: 'Keyword cluster plan.',
        debuggingProof: 'Marks data as verified only when tools/sources are available.',
        bestProvider: 'gemini-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'provider/tool dependent',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['search API connector'],
        copyPromptTemplate: 'Plan SEO clusters for this product. Use real search data only if tools are connected.',
      }),
      member({
        id: 'keyword-trend-scout',
        name: 'Keyword/Trend Scout',
        role: 'Trend collector.',
        narrowJob: 'Find trending phrases, questions, and competitor angles when tools exist.',
        skills: ['trend scouting', 'competitor notes', 'opportunity scoring'],
        memory: 'Uses daily ideation notes.',
        visibleWorkOutput: 'Trend shortlist with confidence.',
        debuggingProof: 'Separates sourced trends from hypotheses.',
        bestProvider: 'gemini-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'tool dependent',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['browser/search connector'],
        copyPromptTemplate: 'Scout trends for this niche. Recommend 3 angles and state data limitations.',
      }),
      member({
        id: 'wordpress-fixer',
        name: 'WordPress Fixer',
        role: 'Planned CMS repair agent.',
        narrowJob: 'Inspect WordPress/CMS issues only after a safe connector exists.',
        skills: ['CMS triage', 'plugin/theme risk notes'],
        memory: 'Uses CMS setup notes when present.',
        visibleWorkOutput: 'Fix plan, not live edits.',
        debuggingProof: 'Lists exact CMS access missing or used.',
        bestProvider: 'manual',
        status: 'planned',
        requiresDaemon: false,
        requiresApiKey: true,
        billingMode: 'connector dependent',
        canRunNow: 'No. Planned.',
        plannedCapabilities: ['CMS connector', 'draft-only publishing'],
        copyPromptTemplate: 'Plan a safe WordPress fix. Do not log in or publish unless a verified connector and approval exist.',
      }),
      member({
        id: 'content-publisher',
        name: 'Content Publisher',
        role: 'Planned publishing approval lane.',
        narrowJob: 'Prepare publish checklist and drafts; never auto-post.',
        skills: ['publishing checklist', 'metadata', 'approval workflow'],
        memory: 'Uses content calendar notes.',
        visibleWorkOutput: 'Publish checklist and draft metadata.',
        debuggingProof: 'Shows destination and approval status.',
        bestProvider: 'manual',
        status: 'planned',
        requiresDaemon: false,
        requiresApiKey: true,
        billingMode: 'connector dependent',
        canRunNow: 'No. Planned.',
        plannedCapabilities: ['approval-gated CMS publishing'],
        copyPromptTemplate: 'Prepare this content for publishing. Do not post automatically.',
      }),
      member({
        id: 'outreach-drafter',
        name: 'Outreach Drafter',
        role: 'Lead-gen message writer.',
        narrowJob: 'Draft messages from approved persona/context.',
        skills: ['email copy', 'DM drafting', 'personalization'],
        memory: 'Uses audience and offer notes.',
        visibleWorkOutput: 'Draft outreach variants.',
        debuggingProof: 'Lists assumptions and personalization variables.',
        bestProvider: 'qwen-experimental',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'manual/API dependent',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['CRM/export integration'],
        copyPromptTemplate: 'Draft outreach variants. Do not send anything automatically.',
      }),
      member({
        id: 'analytics-reviewer',
        name: 'Analytics Reviewer',
        role: 'Performance summarizer.',
        narrowJob: 'Read provided analytics/export data and recommend next action.',
        skills: ['analytics summary', 'conversion notes', 'content performance'],
        memory: 'Uses prior performance notes.',
        visibleWorkOutput: 'Performance summary and recommendations.',
        debuggingProof: 'Names data provided and data missing.',
        bestProvider: 'gemini-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'manual/export dependent',
        canRunNow: 'Copy-prompt only with pasted data.',
        plannedCapabilities: ['analytics connector'],
        copyPromptTemplate: 'Review this analytics export and recommend next actions. If no data is provided, ask for it.',
      }),
    ],
  },
  {
    id: 'daily-chief-of-staff-team',
    name: 'Daily Chief of Staff Team',
    purpose: 'Summarize the day, prioritize work, update memory, and report progress without requiring email/calendar access.',
    bestUse: 'Daily brief, task prioritization, progress reports, and memory/journal updates.',
    status: 'prompt-orchestrated',
    nextSetupStep: 'Use /brief and /tasks today; add calendar/email connectors later only with explicit permission.',
    workflow: [
      'Daily Brief Agent summarizes known local context.',
      'Task Prioritizer ranks work by impact, risk, and readiness.',
      'Calendar/Email Placeholder Agent marks missing integrations honestly.',
      'Memory/Journaling Agent writes a daily note prompt.',
      'Progress Reporter creates a concise status update.',
    ],
    agents: [
      member({
        id: 'daily-brief-agent',
        name: 'Daily Brief Agent',
        role: 'Chief-of-staff summary agent.',
        narrowJob: 'Summarize current project, provider health, tasks, and next action.',
        skills: ['briefing', 'status synthesis', 'blocker tracking'],
        memory: 'Uses /brief, /tasks, /memory, and progress notes.',
        visibleWorkOutput: 'Daily brief text.',
        debuggingProof: 'States which integrations are not connected.',
        bestProvider: 'ollama-local',
        status: 'live',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local/free or configured Ollama',
        canRunNow: 'Yes as generated prompt/brief.',
        plannedCapabilities: ['scheduled morning brief'],
        copyPromptTemplate: 'Generate a BertOS daily brief from available local context. Do not claim calendar/email access.',
      }),
      member({
        id: 'task-prioritizer',
        name: 'Task Prioritizer',
        role: 'Priority scorer.',
        narrowJob: 'Rank tasks by impact, risk, effort, and provider readiness.',
        skills: ['prioritization', 'risk scoring', 'next-action planning'],
        memory: 'Uses task board and roadmap notes.',
        visibleWorkOutput: 'Ranked next-actions list.',
        debuggingProof: 'Shows scoring reasons.',
        bestProvider: 'gemini-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'CLI/subscription or manual',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['task board scoring automation'],
        copyPromptTemplate: 'Rank these tasks by impact, risk, and readiness. Recommend the next best action.',
      }),
      member({
        id: 'calendar-email-placeholder-agent',
        name: 'Calendar/Email Placeholder Agent',
        role: 'Integration gap reporter.',
        narrowJob: 'Tell the user what would require Gmail/Calendar connectors.',
        skills: ['setup guidance', 'honesty checks'],
        memory: 'Uses integration status only.',
        visibleWorkOutput: 'Missing integration setup notes.',
        debuggingProof: 'Does not fabricate inbox/calendar data.',
        bestProvider: 'manual',
        status: 'planned',
        requiresDaemon: false,
        requiresApiKey: true,
        billingMode: 'connector dependent',
        canRunNow: 'No. Planned.',
        plannedCapabilities: ['Gmail/Calendar digest after connector approval'],
        copyPromptTemplate: 'Explain what calendar/email context is missing and how to connect it later. Do not fabricate events or messages.',
      }),
      member({
        id: 'memory-journaling-agent',
        name: 'Memory/Journaling Agent',
        role: 'Daily journal and memory note writer.',
        narrowJob: 'Capture decisions, progress, and tomorrow plan.',
        skills: ['journaling', 'decision capture', 'memory hygiene'],
        memory: 'Uses local memory and future Obsidian vault.',
        visibleWorkOutput: 'Daily journal note.',
        debuggingProof: 'Lists source session/date.',
        bestProvider: 'ollama-local',
        status: 'live',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local/free or configured Ollama',
        canRunNow: 'Yes as copyable note.',
        plannedCapabilities: ['permissioned markdown writer'],
        copyPromptTemplate: 'Write a daily BertOS journal note. Include decisions, progress, blockers, and next action. No secrets.',
      }),
      member({
        id: 'progress-reporter',
        name: 'Progress Reporter',
        role: 'Status updater.',
        narrowJob: 'Turn work completed into concise shareable status.',
        skills: ['status writing', 'summaries', 'risk notes'],
        memory: 'Uses progress notes and validation results.',
        visibleWorkOutput: 'Status update.',
        debuggingProof: 'Includes commands that passed/failed.',
        bestProvider: 'codex-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'CLI/subscription or copy prompt',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['Slack/Telegram notification draft'],
        copyPromptTemplate: 'Write a concise progress report with completed work, validation, risks, and next step.',
      }),
    ],
  },
  {
    id: 'bertos-maintenance-team',
    name: 'Bert OS Maintenance Team',
    purpose: 'Keep BertOS stable with route smoke, build verification, provider audits, safety checks, and docs updates.',
    bestUse: 'After external agent runs, PR reviews, UI additions, or provider-status changes.',
    status: 'partially-live',
    nextSetupStep: 'Use Codex/daemon for validation and keep route smoke scripts expanding as UI grows.',
    workflow: [
      'Route Smoke Tester verifies important pages and APIs.',
      'Typecheck/Build Fixer patches direct compilation failures.',
      'Safety Auditor runs repo/remote/secret/paid-call checks.',
      'Provider Registry Auditor verifies provider cards and status API.',
      'Documentation Updater records real vs planned behavior.',
    ],
    agents: [
      member({
        id: 'route-smoke-tester',
        name: 'Route Smoke Tester',
        role: 'Route/API availability verifier.',
        narrowJob: 'Check dashboard, builder, playbooks, tasks, memory, settings, agents, and APIs load.',
        skills: ['route smoke', 'browser/HTTP checks', 'failure reporting'],
        memory: 'Uses route list and previous smoke failures.',
        visibleWorkOutput: 'Route smoke table.',
        debuggingProof: 'HTTP status and route path evidence.',
        bestProvider: 'codex-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local verification',
        canRunNow: 'Copy-prompt now; route smoke script can be expanded.',
        plannedCapabilities: ['one-click route smoke in UI'],
        copyPromptTemplate: 'Run BertOS route smoke. Report exact route/status failures and do not fake success.',
      }),
      member({
        id: 'typecheck-build-fixer',
        name: 'Typecheck/Build Fixer',
        role: 'Compilation repair agent.',
        narrowJob: 'Fix direct typecheck/build failures and rerun validation.',
        skills: ['TypeScript', 'Next.js build', 'direct-failure repair'],
        memory: 'Uses terminal output and changed files.',
        visibleWorkOutput: 'Patch and command results.',
        debuggingProof: 'Includes exact TypeScript/build errors before/after.',
        bestProvider: 'codex-cli',
        status: 'copy-prompt',
        requiresDaemon: true,
        requiresApiKey: false,
        billingMode: 'CLI/subscription',
        canRunNow: 'Requires Codex CLI plus daemon.',
        plannedCapabilities: ['Autopilot build-failure trigger'],
        copyPromptTemplate: 'Fix direct typecheck/build failures only. Rerun typecheck/build/safety and report output.',
      }),
      member({
        id: 'safety-auditor',
        name: 'Safety Auditor',
        role: 'Repo and integration guardrail checker.',
        narrowJob: 'Confirm no Sylistly, no secrets, no paid calls, no push, and safety script passes.',
        skills: ['repo safety', 'secret hygiene', 'paid-call gates'],
        memory: 'Uses AGENTS.md and safety script.',
        visibleWorkOutput: 'Safety checklist.',
        debuggingProof: 'Reports safety command and git status.',
        bestProvider: 'codex-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local verification',
        canRunNow: 'Yes via local commands outside UI; daemon helps inside UI.',
        plannedCapabilities: ['pre-apply safety gate'],
        copyPromptTemplate: 'Audit this BertOS change for Sylistly risk, secrets, paid calls, push/merge risk, and validation gaps.',
      }),
      member({
        id: 'provider-registry-auditor',
        name: 'Provider Registry Auditor',
        role: 'Provider metadata and status checker.',
        narrowJob: 'Ensure provider status is truthful and planned tools are labeled planned.',
        skills: ['provider routing', 'status API', 'settings UI'],
        memory: 'Uses provider status route and Settings.',
        visibleWorkOutput: 'Provider registry audit.',
        debuggingProof: 'Lists provider ids and labels checked.',
        bestProvider: 'claude-code',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local inspection',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['scheduled provider audit'],
        copyPromptTemplate: 'Audit provider registry/status and Settings cards. Ensure Hermes/FCC/Qwen/Anti-Gravity/Hyperframes/Remotion are honest.',
      }),
      member({
        id: 'documentation-updater',
        name: 'Documentation Updater',
        role: 'Docs and progress recorder.',
        narrowJob: 'Update README/progress notes with what is real vs planned.',
        skills: ['technical writing', 'release notes', 'roadmap clarity'],
        memory: 'Uses current diff and validation results.',
        visibleWorkOutput: 'README/progress update.',
        debuggingProof: 'Lists files changed and commands passed.',
        bestProvider: 'codex-cli',
        status: 'copy-prompt',
        requiresDaemon: false,
        requiresApiKey: false,
        billingMode: 'local documentation',
        canRunNow: 'Copy-prompt only.',
        plannedCapabilities: ['memory-backed changelog'],
        copyPromptTemplate: 'Update BertOS docs for this change. Make real vs planned explicit and include validation results.',
      }),
    ],
  },
]

export function getAgentTeam(id: AgentTeamId) {
  return AGENT_TEAMS.find(team => team.id === id) ?? AGENT_TEAMS[0]
}

export function buildAgentTeamPrompt(team: AgentTeam, task: string) {
  const orchestration = routePrompt(task, 'auto').orchestration
  return [
    `MISSION TEAM: ${team.name}`,
    '',
    `Purpose: ${team.purpose}`,
    `Best use: ${team.bestUse}`,
    `Status: ${team.status}. This is prompt-orchestrated unless a listed backend is verified.`,
    '',
    'User task:',
    task.trim() || 'Plan and execute a focused BertOS improvement.',
    '',
    'Team workflow:',
    ...team.workflow.map((step, index) => `${index + 1}. ${step}`),
    ...(orchestration ? [
      '',
      'Execution graph:',
      `- Mode: ${orchestration.mode}; max parallel lanes: ${orchestration.maxParallelLanes}`,
      `- Token policy: ~${orchestration.estimatedPromptTokens.toLocaleString()} input tokens; context strategy: ${orchestration.tokenPolicy.contextStrategy}; max output: ${orchestration.tokenPolicy.maxOutputTokens.toLocaleString()}`,
      ...orchestration.executionGroups.map(group => `- ${group.mode}: ${group.laneIds.join(', ')} — ${group.reason}`),
      ...orchestration.approvalReasons.map(reason => `- Approval gate: ${reason}`),
    ] : []),
    '',
    'Agent roles:',
    ...team.agents.map(agent => [
      `- ${agent.name} (${agent.role})`,
      `  Narrow job: ${agent.narrowJob}`,
      `  Best provider: ${agent.bestProvider}`,
      `  Status: ${agent.status}; can run now: ${agent.canRunNow}`,
      `  Output proof: ${agent.visibleWorkOutput}; ${agent.debuggingProof}`,
      agent.warning ? `  Warning: ${agent.warning}` : '',
    ].filter(Boolean).join('\n')),
    '',
    'Safety rules:',
    ...COMMON_SAFETY.map(item => `- ${item}`),
    '',
    'Handoff requirements:',
    '- Each agent must show what it produced.',
    '- Planned agents must output setup/implementation prompts, not fake results.',
    '- Codex Build Verifier must run or request typecheck/build/safety validation for code changes.',
    '- Memory Logger must produce a concise session summary when the workflow ends.',
    '',
    'Final report:',
    '- Team roles used',
    '- Work produced by each role',
    '- Files changed or planned files',
    '- Validation evidence',
    '- What is live vs planned',
    '- Next setup step',
  ].join('\n')
}
